port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: "*"
ipv6: true

mode: rule

log-level: warning
external-controller: '0.0.0.0:9090'
secret: "password"
experimental:
  ignore-resolve-fail: true
  
dns:
  enable: true
  listen: 0.0.0.0:53135
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - 114.114.114.114
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
    - https://public.dns.iij.jp/dns-query
    
  enhanced-mode: redir-host
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/32
